{% set version = "2.2" %}
{% set sha256 = "d4f49682f0d20e36d5b64aa3b329bc216f74205eea19ec3e7dbe657ee8edfeac" %}

package:
  name: probeit
  version: {{ version }}

build:
  number: 0
  
source:
  url: "https://github.com/steineggerlab/probeit/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make
  host:
    - pip
    - python >=3.10
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - numpy>=1.16.5
    - pandas
    - biopython
    - mmseqs2 >=13.45111
    - genmap
    - seqkit
    - primer3-py
    - bedtools
    - libgcc-ng >=9.4.0
    - ca-certificates
    - zlib >=1.2.11
    - libzlib >=1.2.11
    - openssl >=1.1.1l
    - python_abi >=3.7
    - pypy3.6 >=7.3.2
    - xz >=5.2.5
    - six >=1.5
    - setuptools

test:
  commands:
    - setcover > /dev/null
    - probeit > /dev/null

about:
  home: https://github.com/steineggerlab/probeit
  summary: "Probeit: a probe designer for detecting and genotyping pathogen!!!"
  license: AGPL-3.0

