{% set version = "0.0.6" %}

package:
  name: consplice
  version: {{ version }}

source:
  url: https://github.com/mikecormier/ConSplice/archive/v{{ version }}.tar.gz
  sha256: 04894951232ae3cba8c84fe9129e9d10bbefa276d8d14e3a76f4b5da1b7671a4 

build:
    number: 0
    noarch: python
    entry_points:
      - consplice = consplice.__main__:main
    script: "python -m pip install . --no-deps --ignore-installed -vv" 

requirements:
  host:
    - pip
    - python
  run:
    - cyvcf2
    - ggd
    - interlap
    - numpy 
    - pandas
    - pyfaidx
    - pyranges=0.0.92
    - ncls=0.0.53
    - pysam
    - scipy
    - pyyaml
    - gsort
    - bcftools
    - htslib
    - biopython
    - gsort>=0.1.4
    - scikit-learn

test:
  commands:
    - consplice --version
    - consplice -h
    - consplice constraint -h
    - consplice ML -h

about:
  home: https://github.com/mikecormier/ConSplice
  docs: https://github.com/mikecormier/ConSplice
  license: MIT
  summary: "ConSplice is a python module used to (1) generate a statistical metric that models the splicing constraint in the human genome, and (2) an ensembl machine learning metric to score genetic variants for pathogenic splicing."

